export const GAME_TICK_DURATION_IN_MS = 1000;
export const MARKET_OPENING_HOUR = 8;
export const MARKET_CLOSING_HOUR = 20;
export const TIME_BETWEEN_NEW_HEALTH_IN_TICK = 3600;
export const TIME_BETWEEN_NEW_NEWS_REPORT_ATTEMPT_IN_TICK = 150;
export const NEW_NEWS_REPORT_PROBABILITY = 0.3;