version: '3.1'

services:
  postgres-iam:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: iam
      POSTGRES_PASSWORD: postgres
    ports:
      - 127.0.0.1:5433:5432
    volumes:
      - ./docker/postgres/iam:/var/lib/postgresql/data

  redis-iam:
    image: redis
    ports:
      - 127.0.0.1:6380:6379
    command:
      - /bin/sh
      - -c
      - redis-server --save 20 1
    volumes:
      - ./docker/redis/iam:/data

  postgres-game:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: game
      POSTGRES_PASSWORD: postgres
    ports:
      - 127.0.0.1:5434:5432
    volumes:
      - ./docker/postgres/game:/var/lib/postgresql/data
