version: '3.8'

services:
  authentication:
    build: Gateway/Authentication/
    ports:
      - 127.0.0.1:30000:30000
    restart: unless-stopped

  launcher:
    build: Gateway/Launcher/
    ports:
      - 127.0.0.1:30001:30001
    restart: unless-stopped

  query:
    build: Gateway/Query/
    ports:
      - 127.0.0.1:30002:30002
    restart: unless-stopped

  command:
    build: Gateway/Command/
    ports:
      - 127.0.0.1:30003:30003
    restart: unless-stopped

  postgres-iam:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: iam
      POSTGRES_PASSWORD: postgres
    ports:
      - 127.0.0.1:5433:5432
    volumes:
      - ./docker/postgres/iam:/var/lib/postgresql/data

  redis-iam:
    image: redis
    ports:
      - 127.0.0.1:6380:6379
    command:
      - /bin/sh
      - -c
      - redis-server --save 20 1
    volumes:
      - ./docker/redis/iam:/data

  postgres-launcher:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: launcher
      POSTGRES_PASSWORD: postgres
    ports:
      - 127.0.0.1:5434:5432
    volumes:
      - ./docker/postgres/launcher:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres-game:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: game
      POSTGRES_PASSWORD: postgres
    ports:
      - 127.0.0.1:5435:5432
    volumes:
      - ./docker/postgres/game:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
